apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-map-viewer
  labels:
    app: dictionary-map-viewer-test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-map-viewer-test2
  template:
    metadata:
      labels:
        app: dictionary-map-viewer-test2
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: dictionary-map-viewer-test2
        image: your-image-name
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000690000
          runAsGroup: 1000690000
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL