apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-map-viewer
  labels:
    app: dictionary-map-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-map-viewer
  template:
    metadata:
      labels:
        app: dictionary-map-viewer
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: dictionary-map-viewer
        image: your-image-name
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: dictionary-map-viewer
  labels:
    app: dictionary-map-viewer
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dictionary-map-viewer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dictionary-map-viewer
  labels:
    app: dictionary-map-viewer
spec:
  host: dictionary-map-viewer-test2-uralic-amazonian-collaboration.2.rahtiapp.fi
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: dictionary-map-viewer
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect