apiVersion: apps/v1
kind: Deployment
metadata:
  name: Dictionary-Map-Viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Dictionary-Map-Viewer
  template:
    metadata:
      labels:
        app: Dictionary-Map-Viewer
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: Dictionary-Map-Viewer
        image: your-image-name
        ports:
        - containerPort: 3838
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
