apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-map-viewer
  labels:
    app: dictionary-map-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dictionary-map-viewer
  template:
    metadata:
      labels:
        app: dictionary-map-viewer
    spec:
      containers:
      - name: dictionary-map-viewer
        image: your-image-name
        ports:
        - name: http
          containerPort: 3838
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 3838
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3838
          initialDelaySeconds: 30
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m"